name: Deploy workflow

on:
  workflow_call:
    secrets:
      CLEVER_TOKEN:
        required: true
      CLEVER_SECRET:
        required: true
      CLEVER_APP_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        name: Setup Nodejs
        with:
          node-version: lts/*
      - run: npm install -g clever-tools
        name: Install clever-tools
      - run: clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        name: Login
      - run: clever link $CLEVER_APP_ID
        env:
          CLEVER_APP_ID: ${{ secrets.clever_app_id }}
        name: Link application
      - run: clever deploy --force
        name: Deploy application
        timeout-minutes: 15
